### ISSUE TITLE
Plus support

### ISSUE THREAD

**Issue by ebabel** [ponewheel/android-ponewheel#2]
Any idea if the plus has a similar API?

**Comment by kwatkins** [comment]
It does. There are more ride modes that I'm updating the app with (just got
a OW+) and will release that soon!

**Comment by ebabel** [comment]
Would love to see your progress if you want to commit to a branch. I'd like to fork and start working on it too.

**Comment by kwatkins** [comment]
@ebabel just wrapping up OW+, also cleaned up some BT workflow and and now scan the service UUID for OW, seemed to fix all connection delays and issues. I'll have it checked in later today and will update here, it should be ready for you to run with.

**Comment by kwatkins** [comment]
Also the official app has improved a lot, big motivation of doing this app was because official app was so behind... I still find myself going to this app for being able to quickly change ride modes during the ride and custom/brighter lights. I didn't see any new BLE characteristics/endpoints with OW+ so the good thing, other than added ride modes, is this app works fine with OW+. 

@ebabel one thing that would be nice to have feature wise is the firmware upgrades, being able to load custom firmware - the updated official app of OW has the feature in there and with a little reverse engineering it should be possible to figure out how it works. Just it has the risk factor going on, hate to brick this lovely slab of technology.

**Comment by ebabel** [comment]
Sounds great, thanks!! I was connecting last night but getting the status 133 issue on my Samsung sometimes. And my oreo phone didn't connect at all. I can't imagine I'll be able to help much on the firmware side, but maybe a better interface for looking at your ride then what they have. Was even considering audible speedo when >17mph could be helpful.

**Comment by kwatkins** [comment]
#9  should close out OW+ support. There is a slight UI bug (might show 2 enabled settings) but it seems to work well enough.

**Comment by kwatkins** [comment]
Seems we can close this, @ebabel merged the updates and by default OW+ is enabled now.
